name: Generate Requirements PDF and HTML

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  build-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Pandoc and LaTeX
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc texlive-latex-base texlive-latex-recommended texlive-latex-extra

      - name: Generate PDF
        run: |
          pandoc requirements.md \
            --toc \
            --number-sections \
            -o requirements-E-store.pdf

      - name: Generate HTML
        run: |
          pandoc requirements.md \
            --toc \
            --number-sections \
            -o requirements-E-store.html

      - name: Upload PDF to Release
        uses: softprops/action-gh-release@v1
        with:
          files: requirements-E-store.pdf

      - name: Upload HTML to Release
        uses: softprops/action-gh-release@v1
        with:
          files: requirements-E-store.html
